### ISSUE TITLE
Can add GPU support

### ISSUE THREAD

**Issue by zyd16888** [loiccoyle/phomo#3]
In order to make the tile image more clear, the size of the master image needs to be large, and the calculation will take a lot of time. If GPU support can be introduced, the situation will be improved.

**Comment by loiccoyle** [comment]
I don't know how to add GPU support, perhaps an easier alternative is to compute the distance matrix on a small master image and then construct the photo mosaic on a larger one. This would require changes to the [`Mosaic.build`](https://github.com/loiccoyle/phomo/blob/master/phomo/mosaic.py#L144) method, but it should be feasible. Feel free to open a PR if you want to implement it 😀

**Comment by loiccoyle** [comment]
> perhaps an easier alternative is to compute the distance matrix on a small master image and then construct the photo mosaic on a larger one

I got around to implementing this workaround, an example is shown in the [`performence_trick`](https://github.com/loiccoyle/phomo/blob/master/examples/performence_trick.ipynb) notebook. Let me know if this helps with your issue.

**Comment by zyd16888** [comment]
Glad to see this solution, I tried to run [performence_trick](https://github.com/loiccoyle/phomo/blob/master/examples/performence_trick.ipynb) notebook uses different image libraries. It is effective, greatly saves the calculation time, and can obtain a high-resolution image more quickly
